export * from './getCoinHistory'
export * from './getCoinColor'
export * from './getCoinData'
export * from './getSupportedCurrencies'
export * from './getGlobalData'
export * from './getCoinHistory'
export * from './getExchangeRates'
export * from './getNewsFeed'